        <div class="row">
            <form action="/cow/list" method="post">
                 <input type="submit" name="active" value="Active" class="btn btn-default">
                 <input type="submit" name="notactive" value="Not Active" class="btn btn-default">
                 <input type="submit" name="all" value="All Cows" class="btn btn-default">
                 <a href='/cow/add' class="btn btn-success">Add Cow</a>
            </form>
        </div>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                      <tr>
                        <th>Active</th>
                        <th>Tag</th>
                        <th>Acquired</th>
                        <th>Type</th>
                        <th>Breed</th>
                        <th>Description</th>
                        <th>Weight</th>
                        <th>Dam</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                      </tr>
                    </thead>
                    <tbody>
                        <?php 
                        $cows = $this->cows;
                        foreach($cows as $key=>$cow){ 
                            ?>
                            <tr>
                                <td><?php echo $cow['active']; ?></td>
                                <td>
                                    <?php
                                        if(!$cow['tag']){
                                            echo $cow['newtag'];
                                        }else{
                                            echo $cow['tag'];
                                        }
                                    ?>
                                </td>
                                <td><?php echo $cow['acquired']; ?></td>
                                <td><?php echo $cow['type']; ?></td>
                                <td><?php echo $cow['breed']; ?></td>
                                <td><?php echo $cow['description']; ?></td>
                                <td><?php echo $cow['weight']; ?></td>
                                <td><?php echo $cow['tagdam']; ?></td>
                                <td><a href='/cow/edit/<?=$cow['id']; ?>' class="btn btn-primary">Edit</a></td>
                                <td><a href='/cow/delete/<?=$cow['id']; ?>' class="btn btn-danger" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Are you sure?" data-content=" This cannot be undone!">Delete</a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>